block_cipher = None

a = Analysis(
    ['main.py'],
    pathex=[],
    binaries=[],
    datas=[
        ('resources', 'resources'),
        ('editor', 'editor'),
        ('terminal_tools', 'terminal_tools'),
        ('utils', 'utils'),
    ],
    hiddenimports=[
        'pygments.lexers',
        'pygments.styles',
        'git',
        'aiohttp',
        'speedtest',
        'ping3',
        'psutil',
        'requests',
        'colorama',
        'pint',
        'forex_python',
        'prompt_toolkit',
        'os',
        'sys',
        'update_manager',
        'deep_translator',
        'nltk',
        'requests',
        'json',
        'os',
        'sys',
        'subprocess',
        'pkg_resources',
        'concurrent.futures',
        'PyQt5',
        'PyQt5.QtWidgets',
        'PyQt5.QtCore',
        'PyQt5.QtGui',
        'PyQt5.QtNetwork',
        'PyQt5.QtWebEngineWidgets',
        'arabic_reshaper',
        'requests',
        'importlib',
        'numpy',
        'pickle5',
        'dill',
        'pandas',
        'matplotlib',
        'scikit-learn',
        'scipy',
        'statsmodels',
        'seaborn',
        'bidi'
        
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    [],
    exclude_binaries=True,
    name='قرطاس',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    console=True,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    onefile=True
)

coll = COLLECT(
    exe,
    a.binaries,
    a.zipfiles,
    a.datas,
    strip=False,
    upx=True,
    upx_exclude=[],
    name='قرطاس',
    onefile=True
)